# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea75d6de84c5af783053f1492f81fffd63410af2dbec4be2d1d95d58f314ce491f1778d8c8f746785ff94786fe5cc2a24d7048b71c8c7c3fe05016472bd25f07

test:
  secret_key_base: 93cdc81175300b561b39eac80c3afaf378eceb3b80173784c3e88abda94e88cce798e46c51c8e5d4c5b249fed58e831c63030743f795214dbc627862e89febc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
